# Generated by Django 4.2.26 on 2025-11-11 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0004_booking_archived_at_booking_archived_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='archived_at',
            new_name='customer_archived_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='is_archived',
            new_name='is_archived_customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='archived_by',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_archived_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_archived_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='supervisor_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='supervisor_archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_archived_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
