# Generated by Django 4.2.26 on 2025-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_archived_at_booking_customer_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
