# Generated by Django 4.2.26 on 2025-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_timeslot_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
