# Generated by Django 4.2.26 on 2025-11-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_timeslot_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
