# Generated by Django 5.2.7 on 2025-11-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
